const productsData = [
  {
    name: "Wireless Bluetooth Headphones",
    description:
      "Over-ear wireless headphones with noise isolation and deep bass",
    price: 2499,
    image: "https://via.placeholder.com/150",
    category: "Electronics",
  },
  {
    name: "Gaming Mouse",
    description: "Ergonomic RGB gaming mouse with adjustable DPI",
    price: 1199,
    image: "https://via.placeholder.com/150",
    category: "Accessories",
  },
  {
    name: "Mechanical Keyboard",
    description: "Compact mechanical keyboard with blue switches",
    price: 3499,
    image: "https://via.placeholder.com/150",
    category: "Accessories",
  },
  {
    name: "Laptop Stand",
    description: "Adjustable aluminum laptop stand for better posture",
    price: 1399,
    image: "https://via.placeholder.com/150",
    category: "Office",
  },
  {
    name: "USB-C Hub",
    description: "6-in-1 USB-C hub with HDMI and USB ports",
    price: 1899,
    image: "https://via.placeholder.com/150",
    category: "Electronics",
  },
  {
    name: "Smartphone Tripod",
    description: "Flexible tripod for smartphones and action cameras",
    price: 899,
    image: "https://via.placeholder.com/150",
    category: "Photography",
  },
  {
    name: "Portable Power Bank 20000mAh",
    description: "Fast charging power bank with dual USB output",
    price: 1799,
    image: "https://via.placeholder.com/150",
    category: "Electronics",
  },
  {
    name: "Wireless Earbuds",
    description: "True wireless earbuds with touch controls",
    price: 2199,
    image: "https://via.placeholder.com/150",
    category: "Electronics",
  },
  {
    name: "Phone Case",
    description: "Shockproof transparent phone case",
    price: 499,
    image: "https://via.placeholder.com/150",
    category: "Accessories",
  },
  {
    name: "Desk Organizer",
    description: "Multi-compartment desk organizer for office supplies",
    price: 799,
    image: "https://via.placeholder.com/150",
    category: "Office",
  },
  {
    name: "Fitness Smart Band",
    description: "Activity tracker with heart rate monitoring",
    price: 2499,
    image: "https://via.placeholder.com/150",
    category: "Fitness",
  },
  {
    name: "Water Bottle (Steel)",
    description: "Insulated stainless steel water bottle (1L)",
    price: 999,
    image: "https://via.placeholder.com/150",
    category: "Lifestyle",
  },
  {
    name: "Backpack",
    description: "Water-resistant backpack with laptop compartment",
    price: 2299,
    image: "https://via.placeholder.com/150",
    category: "Lifestyle",
  },
  {
    name: "Table Lamp",
    description: "LED desk lamp with adjustable brightness",
    price: 1499,
    image: "https://via.placeholder.com/150",
    category: "Home",
  },
  {
    name: "Bluetooth Speaker",
    description: "Portable Bluetooth speaker with powerful sound",
    price: 2699,
    image: "https://via.placeholder.com/150",
    category: "Electronics",
  },
  {
    name: "Wireless Charging Pad",
    description: "Fast wireless charging pad for smartphones",
    price: 1299,
    image: "https://via.placeholder.com/150",
    category: "Electronics",
  },
  {
    name: "Notebook Set",
    description: "Pack of 3 ruled notebooks for daily use",
    price: 399,
    image: "https://via.placeholder.com/150",
    category: "Stationery",
  },
  {
    name: "Pen Stand",
    description: "Minimal metal pen holder for desk",
    price: 299,
    image: "https://via.placeholder.com/150",
    category: "Stationery",
  },
  {
    name: "Yoga Mat",
    description: "Non-slip yoga mat for home workouts",
    price: 999,
    image: "https://via.placeholder.com/150",
    category: "Fitness",
  },
  {
    name: "Cable Organizer",
    description: "Silicone cable organizer clips (pack of 5)",
    price: 349,
    image: "https://via.placeholder.com/150",
    category: "Accessories",
  },
];

export default productsData;
